apiVersion: v1
kind: Service
metadata:
  name: naavre-visualizer-service
  namespace: argo
spec:
  selector:
    app: naavre-visualizer
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: naavre-visualizer-deployment
#   namespace: argo
#   labels:
#     app.kubernetes.io/name: naavre-visualizer
# spec:
#   replicas: 1  # Set the number of desired replicas
#   selector:
#     matchLabels:
#       app: naavre-visualizer
#   template:
#     metadata:
#       labels:
#         app: naavre-visualizer
#     spec:
#       containers:
#       - name: naavre-visualizer
#         image: qcdis/geotiff_viewer:v0.2.6
#         command: ["/bin/sh", "-c"]
#         args:
#             - python /app/python_scripts/main.py
#                 --hostname WEBDAV_HOSTNAME
#                 --mode webdav
#                 --password WEBDAV_PASSWORD
#                 --remote /webdav/vl-laserfarm/geotiffs/
#                 --output /tmp/data
#                 --num 1
#                 --username WEBDAV_USERNAME
#                 && npm start
#         ports:
#         - containerPort: 5173
#           protocol: TCP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: naavre-visualizer-ingress
  namespace: argo
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: HOSTNAME
      http:
        paths:
          - path: /naavre-visualizer(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: naavre-visualizer-service
                port:
                  number: 5173

