apiVersion: v1
kind: Service
metadata:
  name: naavre-visualizer-service
  namespace: argo
spec:
  selector:
    app.kubernetes.io/name: naavre-visualizer
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: naavre-visualizer-ingress
  namespace: argo
  labels:
    app.kubernetes.io/name: naavre-visualizer
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Accept-Encoding "";
      sub_filter '<base href="/">' '<base href="/naavre-visualizer/">';
      sub_filter_once on;
      more_set_headers "X-Accel-Buffering: no";
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: HOST
      http:
        paths:
          - path: /naavre-visualizer(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: naavre-visualizer-service
                port:
                  number: 5173
