apiVersion: v1
kind: Service
metadata:
  name: naavre-visualization-service
spec:
  type: NodePort
  selector:
    app: naavre-visualization
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 31000
      nodePort: 31000
