apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: naavre-workflow
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: adeelaashraf/naavre_visualization:latest
        imagePullPolicy: Always

